### PR TITLE
Fix : multi categories + header comments

### LINKED ISSUE #18: Map Item can have multiple categories

### LINKED ISSUE #19: Module "location list" 's configuration features search not taken into account in template
Map location list template does not have the code to display search form despite it is possible to configure one in the module

### LINKED ISSUE #20: Legend & Markers fix
Map uses filters to parse categories config. Use `categories` var instead.

`vendor/webexmachina/contao-geodata/src/Resources/public/js/default.js` l52
`vendor/webexmachina/contao-geodata/src/Resources/public/js/leaflet.js` l51

### LINKED ISSUE #22: Add meta in reader module
When loading a geodata reader module, override title and description meta tags by the current location.

### LINKED ISSUE #23: Update breadcrumb when on a reader module
By default, Contao loads the reader page with its title, usually a generic one like "Geodata Reader", which is not very great for readability and ergonomy.
Use the Contao hook to update the breadcrumb and replace the last item by the title of the current location

### PR DESCRIPTION
**Pull request by ChipsVII**
- Header comments fixed in files
- Items can have multiple categories
- Maps have a default category

### CODE REVIEW

**Review by LupusVII — COMMENTED** [review]
Does the issue #20 and the fix planned is compatible with this PR? Or should it be updated according to this PR?

**Comment by ChipsVII** [comment]
> Does the issue #20 and the fix planned is compatible with this PR? Or should it be updated according to this PR?

This PR does not resolve issue #20 . Should it, while we're at it ?

**Comment by LupusVII** [comment]
Let's tag @SeptimusVII so he can check and add his changes here. Maybe there is more to fix than I saw when I made the issue.

**Comment by ChipsVII** [comment]
@SeptimusVII 
Could you do your magic for filters in `mod_wem_geodata_list.html5` template ? I added the code, they work, but it looks ... raw

**Comment by SeptimusVII** [comment]
> @SeptimusVII Could you do your magic for filters in `mod_wem_geodata_list.html5` template ? I added the code, they work, but it looks ... raw

in a list module without map displayed, changing the filters location has no meaning; they should always be on top of the list.
So the selector "filters" should be replaced by a simple checkbox, controlling whether we want to display filters or not.

**Comment by ChipsVII** [comment]
> in a list module without map displayed, changing the filters location has no meaning; they should always be on top of the list. So the selector "filters" should be replaced by a simple checkbox, controlling whether we want to display filters or not.

Done, and deployed in our second sandbox.

**Pull request merged**
